
// DEBUG

#define ASSERSIONS
#define CONSOLE_LOG
// #define FILE_LOG

// RENDERING

#define METERS_TO_PIXELS 32.0f
#define PIXELS_TO_METERS (1/METERS_TO_PIXELS)
#define CHUNK_SIZE_METERS 25.0f
#define CHUNK_SIZE_PIXELS (CHUNK_SIZE_METERS*METERS_TO_PIXELS)
