
// DLL
#define ENGINE_EXPORTS

// DEBUG
#define ASSERSIONS
#define CONSOLE_LOG
// #define FILE_LOG

// MAP
#define CHUNK_SIZE_METERS 25.0f
#define CHUNK_SIZE_PIXELS (CHUNK_SIZE_METERS*METERS_TO_PIXELS)
